[project]
name = 'RealEstateTokenization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.property-manager]
path = 'contracts/property-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.property-tokenizer]
path = 'contracts/property-tokenizer.clar'
clarity_version = 3
epoch = 3.1

[contracts.rent-distributor]
path = 'contracts/rent-distributor.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
